find . -type f | while read -r file; do
    type=$(file -b --mime-type "$file")
    case "$type" in
    "image/jpeg")
        ext=".jpg"
        ;;
    "image/png")
        ext=".png"
        ;;
    "image/gif")
        ext=".gif"
        ;;
    "image/bmp" | "image/x-ms-bmp")
        ext=".bmp"
        ;;
    "image/tiff")
        ext=".tiff"
        ;;
    "image/x-canon-cr2")
        ext=".cr2"
        ;;
    "image/x-nikon-nef")
        ext=".nef"
        ;;
    "image/x-olympus-orf")
        ext=".orf"
        ;;
    "image/x-panasonic-rw2")
        ext=".rw2"
        ;;
    "image/x-pentax-pef")
        ext=".pef"
        ;;
    "image/x-sony-arw")
        ext=".arw"
        ;;
    "image/x-ico" | "image/vnd.microsoft.icon")
        ext=".ico"
        ;;
    "image/webp")
        ext=".webp"
        ;;
    "image/vnd.adobe.photoshop")
        ext=".psd"
        ;;
    "image/x-xbitmap")
        ext=".xbm"
        ;;
    "image/x-xpixmap")
        ext=".xpm"
        ;;
    "image/svg+xml")
        ext=".svg"
        ;;
    "image/x-tga")
        ext=".tga"
        ;;
    "application/octet-stream")
        ext=".octet-stream"
        ;;
    "application/json")
        ext=".json"
        ;;
    "application/x-dbt")
        ext=".dbt"
        ;;
    "application/x-stargallery-thm")
        ext=".stargallery-thm"
        ;;
    "application/CDFV2")
        ext=".cdfv2"
        ;;
    "application/zlib")
        ext=".zlib"
        ;;
    "application/gzip" | "application/x-gzip")
        ext=".gz"
        ;;
    "application/x-tex-tfm")
        ext=".tfm"
        ;;
    "inode/x-empty")
        ext=".empty"
        ;;
    "application/x-ms-sdi")
        ext=".sdi"
        ;;
    "application/pdf")
        ext=".pdf"
        ;;
    "text/plain")
        ext=".txt"
        ;;
    "application/zip")
        ext=".zip"
        ;;
    "application/x-rar-compressed")
        ext=".rar"
        ;;
    "application/x-tar")
        ext=".tar"
        ;;
    "application/x-7z-compressed")
        ext=".7z"
        ;;
    "application/vnd.ms-powerpoint")
        ext=".ppt"
        ;;
    "application/vnd.ms-excel")
        ext=".xls"
        ;;
    "application/msword")
        ext=".doc"
        ;;
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document")
        ext=".docx"
        ;;
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
        ext=".xlsx"
        ;;
    "application/vnd.mozilla.xul+xml" | "application/xhtml+xml")
        ext=".xul"
        ;;
    "application/x-javascript")
        ext=".js"
        ;;
    "application/x-shockwave-flash" | "application/x-shockwave-flash2-preview")
        ext=".swf"
        ;;
    "audio/mpeg")
        ext=".mp3"
        ;;
    "audio/ogg")
        ext=".ogg"
        ;;
    "audio/wav" | "audio/x-wav")
        ext=".wav"
        ;;
    "image/x-ms-bmp")
        ext=".bmp"
        ;;
    "image/icon")
        ext=".ico"
        ;;
    "image/svg+xml")
        ext=".svg"
        ;;
    "text/csv" | "application/csv")
        ext=".csv"
        ;;
    "text/html")
        ext=".html"
        ;;
    "text/xml")
        ext=".xml"
        ;;
    "video/avi" | "video/x-msvideo")
        ext=".avi"
        ;;
    "video/mp4")
        ext=".mp4"
        ;;
    "video/mpeg")
        ext=".mpeg"
        ;;
    "video/quicktime")
        ext=".mov"
        ;;
    "video/x-ms-wmv")
        ext=".wmv"
        ;;
    "video/x-flv")
        ext=".flv"
        ;;
    "video/x-matroska")
        ext=".mkv"
        ;;
    "video/x-ms-asf")
        ext=".asf"
        ;;
    "video/webm")
        ext=".webm"
        ;;
    "video/x-avi")
        ext=".avi"
        ;;
    "video/x-f4v")
        ext=".f4v"
        ;;
    "video/x-fli")
        ext=".fli"
        ;;
    "video/x-flv")
        ext=".flv"
        ;;
    "video/x-m4v")
        ext=".m4v"
        ;;
    "video/x-mng")
        ext=".mng"
        ;;
    "video/x-ms-asf")
        ext=".asf"
        ;;
    "video/x-ms-wm")
        ext=".wm"
        ;;
    "video/x-ms-wmv")
        ext=".wmv"
        ;;
    "video/x-ms-wmx")
        ext=".wmx"
        ;;
    "video/x-ms-wvx")
        ext=".wvx"
        ;;
    "video/x-nsv")
        ext=".nsv"
        ;;
    "video/x-ogm")
        ext=".ogm"
        ;;
    "video/x-mpegurl")
        ext=".m3u"
        ;;
    "video/3gpp")
        ext=".3gp"
        ;;
    "video/3gpp2")
        ext=".3g2"
        ;;
    "video/vnd.rn-realvideo")
        ext=".rv"
        ;;
    "video/vnd.vivo")
        ext=".viv"
        ;;
    "video/x-dv")
        ext=".dv"
        ;;
    "video/x-ms-dvr")
        ext=".dvr-ms"
        ;;
    "application/x-dosexec")
        ext=".exe"
        ;;
    "image/x-tga")
        ext=".tga"
        ;;
    "application/x-wine-extension-ini")
        ext=".ini"
        ;;
    "application/vnd.ms-cab-compressed")
        ext=".cab"
        ;;
    "application/vnd.ms-msi" | "application/x-msi")
        ext=".msi"
        ;;
    "application/vnd.ms-outlook")
        ext=".pst"
        ;;
    "application/winhelp")
        ext=".hlp"
        ;;
    "audio/midi")
        ext=".mid"
        ;;
    "application/x-sqlite3")
        ext=".sqlite3"
        ;;
    "application/dicom")
        ext=".dcm"
        ;;
    "application/epub+zip")
        ext=".epub"
        ;;
    "application/java-archive" | "application/x-java-archive")
        ext=".jar"
        ;;
    "application/javascript" | "application/x-javascript")
        ext=".js"
        ;;
    "application/postscript")
        ext=".ps"
        ;;
    "application/vnd.iccprofile")
        ext=".icc"
        ;;
    "application/vnd.lotus-1-2-3")
        ext=".123"
        ;;
    "application/vnd.ms-fontobject")
        ext=".eot"
        ;;
    "application/vnd.ms-office")
        ext=".office"
        ;;
    "application/vnd.ms-opentype")
        ext=".otf"
        ;;
    "application/vnd.openxmlformats-officedocument.presentationml.presentation")
        ext=".pptx"
        ;;
    "application/x-arc")
        ext=".arc"
        ;;
    "application/x-archive")
        ext=".archive"
        ;;
    "application/x-chrome-extension")
        ext=".crx"
        ;;
    "application/x-dosdriver")
        ext=".sys"
        ;;
    "application/x-dxf")
        ext=".dxf"
        ;;
    "application/x-executable")
        ext=".exe"
        ;;
    "application/x-font-sfn")
        ext=".sfn"
        ;;
    "application/x-fptapplication/x-dbt")
        ext=".fpt"
        ;;
    "application/x-gettext-translation")
        ext=".po"
        ;;
    "application/x-hdf")
        ext=".hdf"
        ;;
    "application/x-ima")
        ext=".ima"
        ;;
    "application/x-innosetup")
        ext=".iss"
        ;;
    "application/x-java-keystore")
        ext=".jks"
        ;;
    "application/x-ms-dat")
        ext=".dat"
        ;;
    "application/x-ms-ese")
        ext=".ese"
        ;;
    "application/x-ms-pdb")
        ext=".pdb"
        ;;
    "application/x-ms-sdb")
        ext=".sdb"
        ;;
    "application/x-ms-wim")
        ext=".wim"
        ;;
    "application/x-msaccess")
        ext=".mdb"
        ;;
    "application/x-object")
        ext=".o"
        ;;
    "application/x-rar")
        ext=".rar"
        ;;
    "application/x-riff")
        ext=".riff"
        ;;
    "application/x-setupscript")
        ext=".setup"
        ;;
    "application/x-stuffit")
        ext=".sit"
        ;;
    "application/x-tplink-bin")
        ext=".bin"
        ;;
    "audio/basic")
        ext=".au"
        ;;
    "audio/x-aiff")
        ext=".aiff"
        ;;
    "audio/x-hx-aac-adts")
        ext=".aac"
        ;;
    "audio/x-m4a" | "audio/x-mp4a-latm")
        ext=".m4a"
        ;;
    "font/sfnt")
        ext=".sfnt"
        ;;
    "font/ttf")
        ext=".ttf"
        ;;
    "image/g3fax")
        ext=".g3fax"
        ;;
    "image/heic")
        ext=".heic"
        ;;
    "image/wmf")
        ext=".wmf"
        ;;
    "image/x-eps")
        ext=".eps"
        ;;
    "image/x-icns")
        ext=".icns"
        ;;
    "image/x-win-bitmap")
        ext=".bmp"
        ;;
    "image/x-xcf")
        ext=".xcf"
        ;;
    "message/rfc822")
        ext=".eml"
        ;;
    "text/PGP")
        ext=".pgp"
        ;;
    "text/rtf")
        ext=".rtf"
        ;;
    "text/troff")
        ext=".tr"
        ;;
    "text/x-asm")
        ext=".asm"
        ;;
    "text/x-c")
        ext=".c"
        ;;
    "text/x-c++")
        ext=".cpp"
        ;;
    "text/x-java")
        ext=".java"
        ;;
    "text/x-ms-regedit")
        ext=".reg"
        ;;
    "text/x-msdos-batch")
        ext=".bat"
        ;;
    "text/x-shellscript")
        ext=".sh"
        ;;
    "application/x-ms-wim")
        ext=".wim"
        ;;
    "image/x-award-bioslogo")
        ext=".awdbio"
        ;;
    "application/dicom")
        ext=".dcm"
        ;;
    "application/epub+zip")
        ext=".epub"
        ;;
    "application/java-archive" | "application/x-java-archive")
        ext=".jar"
        ;;
    "application/javascript" | "application/x-javascript")
        ext=".js"
        ;;
    "application/pgp-keys")
        ext=".pgp"
        ;;
    "application/postscript")
        ext=".ps"
        ;;
    "application/vnd.iccprofile")
        ext=".icc"
        ;;
    "application/vnd.lotus-1-2-3")
        ext=".123"
        ;;
    "application/vnd.ms-fontobject")
        ext=".eot"
        ;;
    "application/vnd.ms-office")
        ext=".office"
        ;;
    "application/vnd.ms-opentype")
        ext=".otf"
        ;;
    "application/vnd.openxmlformats-officedocument.presentationml.presentation")
        ext=".pptx"
        ;;
    "application/x-arc")
        ext=".arc"
        ;;
    "application/x-archive")
        ext=".archive"
        ;;
    "application/x-chrome-extension")
        ext=".crx"
        ;;
    "application/x-compress")
        ext=".Z"
        ;;
    "application/x-dosdriver")
        ext=".sys"
        ;;
    "application/x-dvi")
        ext=".dvi"
        ;;
    "application/x-dxf")
        ext=".dxf"
        ;;
    "application/x-dzip")
        ext=".dz"
        ;;
    "application/x-executable")
        ext=".exe"
        ;;
    "application/x-font-sfn")
        ext=".sfn"
        ;;
    "application/x-fptapplication/x-dbt")
        ext=".fpt"
        ;;
    "application/x-gettext-translation")
        ext=".po"
        ;;
    "application/x-hdf")
        ext=".hdf"
        ;;
    "application/x-ima")
        ext=".ima"
        ;;
    "application/x-innosetup")
        ext=".iss"
        ;;
    "application/x-java-keystore")
        ext=".jks"
        ;;
    "application/x-ms-dat")
        ext=".dat"
        ;;
    "application/x-ms-ese")
        ext=".ese"
        ;;
    "application/x-ms-pdb")
        ext=".pdb"
        ;;
    "application/x-ms-sdb")
        ext=".sdb"
        ;;
    "application/x-ms-wim")
        ext=".wim"
        ;;
    "application/x-msaccess")
        ext=".mdb"
        ;;
    "application/x-object")
        ext=".o"
        ;;
    "application/x-pgp-keyring")
        ext=".keyring"
        ;;
    "application/x-rar")
        ext=".rar"
        ;;
    "application/x-riff")
        ext=".riff"
        ;;
    "application/x-setupscript")
        ext=".setup"
        ;;
    "application/x-stuffit")
        ext=".sit"
        ;;
    "application/x-tplink-bin")
        ext=".bin"
        ;;
    "audio/basic")
        ext=".au"
        ;;
    "audio/x-aiff")
        ext=".aiff"
        ;;
    "audio/x-hx-aac-adts")
        ext=".aac"
        ;;
    "audio/x-m4a" | "audio/x-mp4a-latm")
        ext=".m4a"
        ;;
    "font/sfnt")
        ext=".sfnt"
        ;;
    "font/ttf")
        ext=".ttf"
        ;;
    "image/g3fax")
        ext=".g3fax"
        ;;
    "image/heic")
        ext=".heic"
        ;;
    "image/wmf")
        ext=".wmf"
        ;;
    "image/x-award-bioslogo")
        ext=".awdbio"
        ;;
    "image/x-eps")
        ext=".eps"
        ;;
    "image/x-icns")
        ext=".icns"
        ;;
    "image/x-portable-pixmap")
        ext=".ppm"
        ;;
    "image/x-win-bitmap")
        ext=".bmp"
        ;;
    "image/x-xcf")
        ext=".xcf"
        ;;
    "message/rfc822")
        ext=".eml"
        ;;
    "text/PGP")
        ext=".pgp"
        ;;
    "text/rtf")
        ext=".rtf"
        ;;
    "text/troff")
        ext=".tr"
        ;;
    "text/x-asm")
        ext=".asm"
        ;;
    "text/x-c")
        ext=".c"
        ;;
    "text/x-c++")
        ext=".cpp"
        ;;
    "text/x-java")
        ext=".java"
        ;;
    "text/x-ms-regedit")
        ext=".reg"
        ;;
    "text/x-msdos-batch")
        ext=".bat"
        ;;
    "text/x-shellscript")
        ext=".sh"
        ;;

    *)
        echo "Unknown file type: $type"
        echo "Unknown file type: $type" >>/mnt/d/Transfer/unknownFiles.txt
        continue
        ;;
    esac
 
    dir=$(dirname "$file")
    base=$(basename "$file")
    mv "$file" "$dir/${base%.*}$ext"
done
