#!/bin/bash
echo Depecndency Update script started at $(date) >> /var/log/dependency-update-repository.log
#reposync --download_path=/opt/repo/ --downloadcomps --download-metadata
cd /opt/repo/depRepo

# for i in $(ls /opt/repo/remi*); do /usr/local/bin/downloadMe.sh "$i" 1 ; done
# for i in $(ls /opt/docker/el7/remi*); do /usr/local/bin/downloadMe.sh "$i" 1 ; done
# for i in $(ls /opt/docker/el7/*); do /usr/local/bin/downloadMe.sh "$i" 1 ; done
# for i in $(find /opt/docker/el7/ -type f -iname "*.rpm"); do /usr/local/bin/downloadMe.sh "$i" 1 ; done
# for i in $(find /opt/docker/el7/ -type f -iname "*.rpm" -exec basename {} \; | sort -u); do /usr/local/bin/downloadMe.sh "$i" 1 ; done
# find /opt/repo/el7/ -type f -iname "*.rpm" -print0 | parallel -0 'downloadMe.sh "$(basename {})" 1'

dir="$1"

find "$dir" -type f -iname "*.rpm" -print0 | parallel -0 'downloadMe.sh "$(basename {})" "$dir"'


echo Dependency Update script ended at $(date) >> /var/log/dependency-update-repository.log
