#!/bin/bash

function fileExists() {
        if [[ -f "$1" ]]
        then
            echo "$1 exists on your filesystem."
        fi
}

function findingDeps() {
        for i in $(cat /root/remi/otherrepo/deps_u);
                do ( for j in $(rpm -qR "$i");
                        do rpm -q --whatprovides "$j";
                        done | sort | uniq | grep -v "no package provides") | sort -u >> /root/remi/otherrepo/depdeps ;
                done;
        echo
        awk -F "-[0-9]" '{print $1}' /root/remi/otherrepo/depdeps | sort -u > /root/remi/otherrepo/depdeps_u;
#       sort -u /root/remi/otherrepo/depdeps > /root/remi/otherrepo/depdeps_u;
        for i in $(cat /root/remi/otherrepo/depdeps_u);
                do yumdownloader -y --resolve "$i" --downloadonly;
                done;
#        fileExists /root/remi/otherrepo/depsdeps
#        fileExists /root/remi/otherrepo/deps_u
        echo "deps_u has these files:::  "
#        echo "Removing /root/remi/otherrepo/depdeps"
#        echo "Removing /root/remi/otherrepo/deps_u"
#        rm -rf /root/remi/otherrepo/depdeps /root/remi/otherrepo/deps_u;
        mv -f /root/remi/otherrepo/depdeps_u /root/remi/otherrepo/deps_u;
        cat /root/remi/otherrepo/deps_u
}

function downloadDeps(){
        if [ -z $1 ]
        then
                echo "You Must enter write the command like this:  "
                echo "downloadMe.sh <Package_to_Download> <Number_of_recursive_dependency_levels>"
                echo "downloadMe.sh httpd 5"
                echo
                echo
                echo
                exit
        fi

        if [ -z $2 ]
        then
                echo "You didn't enter the recursion level!!!"
                echo "You Must enter write the command like this:  "
                echo "downloadMe.sh <Package_to_Download> <Number_of_recursive_dependency_levels>"
                echo "downloadMe.sh httpd 5"
                echo
                echo
                echo
                exit
        fi

        echo "" > /root/remi/otherrepo/deps
        echo "" > /root/remi/otherrepo/depdeps
        echo "" > /root/remi/otherrepo/deps_u
        echo "" > /root/remi/otherrepo/depdeps_u

        rpm -q --whatprovides $(echo "$1") | sort | uniq | grep -v "no package provides" | sort -u >> /root/remi/otherrepo/deps;

        awk -F "-[0-9]" '{print $1}' /root/remi/otherrepo/deps | sort -u > /root/remi/otherrepo/deps_u;
#       sort -u /root/remi/otherrepo/deps > /root/remi/otherrepo/deps_u;
#       fileExists /root/remi/otherrepo/deps_u

        for i in $(cat /root/remi/otherrepo/deps_u);
                do yumdownloader -y --resolve "$i" --downloadonly;
                done;
#       fileExists /root/remi/otherrepo/deps

        k=0

        echo "recursion is equal to::  $2"
        while [ "$k" -lt "$2" ]
                do
                        findingDeps
                        k=$[$k+1]
                        echo "recursion is equal to::  $k"
                        echo "Levels to go::  $[$2-$k]"
        done
}

downloadDeps "$1" "$2"
